window.sheetData = {
  "updatedAt": "2026-06-04T07:19:23.695Z",
  "f2": {
    "rankings": {
      "Serie A": [
        {
          "position": "01",
          "driver": "JuninhoGameplay",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 33,
          "pointsLabel": "33,00",
          "movement": "🔼 + 2",
          "nc": 2,
          "dnf": "0,00%"
        },
        {
          "position": "02",
          "driver": "lipe0204",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 29.5,
          "pointsLabel": "29,50",
          "movement": "🔼 + 2",
          "nc": 2,
          "dnf": "16,28%"
        },
        {
          "position": "03",
          "driver": "vSpiritWilo",
          "country": "FRA",
          "flag": "🇫🇷",
          "team": "Sem construtor",
          "points": 26,
          "pointsLabel": "26,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "33,33%"
        },
        {
          "position": "04",
          "driver": "Vegenakki",
          "country": "FIN",
          "flag": "🇫🇮",
          "team": "Sem construtor",
          "points": 26,
          "pointsLabel": "26,00",
          "movement": "⏫ + 25",
          "nc": 25,
          "dnf": "0,00%"
        },
        {
          "position": "05",
          "driver": "fjsapi",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 24,
          "pointsLabel": "24,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "06",
          "driver": "Dudu Reeves",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 13,
          "pointsLabel": "13,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "11,11%"
        },
        {
          "position": "07",
          "driver": "Barbudo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 12.5,
          "pointsLabel": "12,50",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "12,50%"
        },
        {
          "position": "08",
          "driver": "I_need_a_DOCTOR",
          "country": "CAN",
          "flag": "🇨🇦",
          "team": "Sem construtor",
          "points": 12,
          "pointsLabel": "12,00",
          "movement": "⏫ + 7",
          "nc": 7,
          "dnf": "38,10%"
        },
        {
          "position": "09",
          "driver": "RuanPbl",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 12,
          "pointsLabel": "12,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "11,11%"
        },
        {
          "position": "10",
          "driver": "LuizVitex",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 12,
          "pointsLabel": "12,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "13,64%"
        },
        {
          "position": "11",
          "driver": "andrxss",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 10,
          "pointsLabel": "10,00",
          "movement": "🔼 + 4",
          "nc": 4,
          "dnf": "33,33%"
        },
        {
          "position": "12",
          "driver": "Srta_Dark_T",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 10,
          "pointsLabel": "10,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "13",
          "driver": "Zana",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 9,
          "pointsLabel": "9,00",
          "movement": "🔽 - 4",
          "nc": -4,
          "dnf": "50,00%"
        },
        {
          "position": "14",
          "driver": "JoaoTwcod",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 8,
          "pointsLabel": "8,00",
          "movement": "🔽 - 4",
          "nc": -4,
          "dnf": "29,17%"
        },
        {
          "position": "15",
          "driver": "UrsoSenna",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 7.5,
          "pointsLabel": "7,50",
          "movement": "🔽 - 4",
          "nc": -4,
          "dnf": "15,38%"
        },
        {
          "position": "16",
          "driver": "ViT1N",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 5,
          "pointsLabel": "5,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "25,00%"
        },
        {
          "position": "17",
          "driver": "Moitipo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 1,
          "pointsLabel": "1,00",
          "movement": "🔽 - 4",
          "nc": -4,
          "dnf": "23,08%"
        },
        {
          "position": "18",
          "driver": "TM Poseidon",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 1,
          "pointsLabel": "1,00",
          "movement": "⏫ + 11",
          "nc": 11,
          "dnf": "27,78%"
        },
        {
          "position": "19",
          "driver": "Glauco [BR]",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 4",
          "nc": -4,
          "dnf": "13,16%"
        },
        {
          "position": "20",
          "driver": "Omg_iz-ghOst",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 4",
          "nc": -4,
          "dnf": "40,00%"
        }
      ],
      "Serie B": [
        {
          "position": "01",
          "driver": "CoyoteLoko",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 4",
          "nc": -4,
          "dnf": "35,71%"
        },
        {
          "position": "02",
          "driver": "back",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔼 + 1",
          "nc": 1,
          "dnf": "33,33%"
        },
        {
          "position": "03",
          "driver": "junniorkz",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔼 + 1",
          "nc": 1,
          "dnf": "50,00%"
        },
        {
          "position": "04",
          "driver": "L1peZxZ",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔼 + 1",
          "nc": 1,
          "dnf": "100,00%"
        },
        {
          "position": "05",
          "driver": "IsmuYa",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏬ - 5",
          "nc": -5,
          "dnf": "57,14%"
        },
        {
          "position": "06",
          "driver": "Enzo24M",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏬ - 5",
          "nc": -5,
          "dnf": "23,53%"
        },
        {
          "position": "07",
          "driver": "Fer",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏬ - 5",
          "nc": -5,
          "dnf": "37,50%"
        },
        {
          "position": "08",
          "driver": "LucastBorges",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏬ - 5",
          "nc": -5,
          "dnf": "50,00%"
        },
        {
          "position": "09",
          "driver": "Tony_Uru",
          "country": "URU",
          "flag": "🇺🇾",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏬ - 5",
          "nc": -5,
          "dnf": "60,00%"
        },
        {
          "position": "10",
          "driver": "PHMN",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏬ - 5",
          "nc": -5,
          "dnf": "50,00%"
        },
        {
          "position": "11",
          "driver": "Rezende_rz",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔼 + 4",
          "nc": 4,
          "dnf": "18,92%"
        },
        {
          "position": "12",
          "driver": "PRTCarvalho",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "15,00%"
        },
        {
          "position": "13",
          "driver": "willaxbox",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "14",
          "driver": "ARM BUNFL",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "15",
          "driver": "BreakingBench",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "16",
          "driver": "GAMER",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "17",
          "driver": "SCHUCHTER",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "18",
          "driver": "shadoww",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "19",
          "driver": "arleking",
          "country": "MEX",
          "flag": "🇲🇽",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "60,00%"
        },
        {
          "position": "20",
          "driver": "deri",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "46,15%"
        }
      ],
      "Serie C": [
        {
          "position": "01",
          "driver": "ReD",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "5,00%"
        },
        {
          "position": "02",
          "driver": "Alexander_Gui",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "71,43%"
        },
        {
          "position": "03",
          "driver": "murf",
          "country": "THA",
          "flag": "🇹🇭",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "04",
          "driver": "millo_bello",
          "country": "CZE",
          "flag": "🇨🇿",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "33,33%"
        },
        {
          "position": "05",
          "driver": "bruno",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "06",
          "driver": "Puga",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "07",
          "driver": "DiegoAnonimo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "08",
          "driver": "Liine e Teteu",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "09",
          "driver": "Paulo Inigo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "5,56%"
        },
        {
          "position": "10",
          "driver": "Max Verstappen",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "22,22%"
        },
        {
          "position": "11",
          "driver": "ValdineyGamer_YT",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "8,00%"
        },
        {
          "position": "12",
          "driver": "ARM_Theuz_B",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "25,00%"
        },
        {
          "position": "13",
          "driver": "Rodrigomaia_",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "7,69%"
        },
        {
          "position": "14",
          "driver": "PHX Erick",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "17,65%"
        },
        {
          "position": "15",
          "driver": "ErbesAE77",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "40,00%"
        },
        {
          "position": "16",
          "driver": "Waitz",
          "country": "COL",
          "flag": "🇨🇴",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "27,78%"
        },
        {
          "position": "17",
          "driver": "deharo",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "18",
          "driver": "Pudim-sweet",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "19",
          "driver": "Albono",
          "country": "THA",
          "flag": "🇹🇭",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "20",
          "driver": "luimatheo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "20,00%"
        }
      ],
      "Serie D": [
        {
          "position": "01",
          "driver": "DH",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "02",
          "driver": "Tin84cho",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "19,05%"
        },
        {
          "position": "03",
          "driver": "BARLAS",
          "country": "CAN",
          "flag": "🇨🇦",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "04",
          "driver": "[CRE] Kobayashi",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "50,00%"
        },
        {
          "position": "05",
          "driver": "Inácio Souza",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "50,00%"
        },
        {
          "position": "06",
          "driver": "Syrunn abandit",
          "country": "TUR",
          "flag": "🇹🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "07",
          "driver": "Alteim",
          "country": "NED",
          "flag": "🇳🇱",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "50,00%"
        },
        {
          "position": "08",
          "driver": "WLucas",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "60,00%"
        },
        {
          "position": "09",
          "driver": "jhursinho",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "10",
          "driver": "FHOPO6",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "11",
          "driver": "Ninetty",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "63,64%"
        },
        {
          "position": "12",
          "driver": "Asce",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "33,33%"
        },
        {
          "position": "13",
          "driver": "Alan Zovedi",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "14",
          "driver": "Murilin",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "50,00%"
        },
        {
          "position": "15",
          "driver": "GuestElkNoise",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "16",
          "driver": "CSC XJhonX",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "17",
          "driver": "PolarBear",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "50,00%"
        },
        {
          "position": "18",
          "driver": "Gustavo COSTA",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "19",
          "driver": "Cabecaloko",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "66,67%"
        },
        {
          "position": "20",
          "driver": "and0nii_s",
          "country": "USA",
          "flag": "🇺🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        }
      ],
      "Serie E": [
        {
          "position": "01",
          "driver": "Motiongod",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "02",
          "driver": "Levelupnarok",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "03",
          "driver": "caetano",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "04",
          "driver": "RaphaelN",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "05",
          "driver": "Maxlp",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "06",
          "driver": "Marl5zxx",
          "country": "GBR",
          "flag": "🇬🇧",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "07",
          "driver": "LeonardoNeto",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "66,67%"
        },
        {
          "position": "08",
          "driver": "Auxiliar de Construção Civil",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "09",
          "driver": "KS7SonDiogo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "10",
          "driver": "tteuwx",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "12,50%"
        },
        {
          "position": "11",
          "driver": "Alejo_Carballo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "12",
          "driver": "joaxsenx",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "13",
          "driver": "blid",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "14",
          "driver": "BRV-MIQUELOTI",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "15",
          "driver": "pudim_doce",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "16",
          "driver": "Alexis Barragan",
          "country": "MEX",
          "flag": "🇲🇽",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "17",
          "driver": "tavares_nt",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "18",
          "driver": "DELTA_Theuxzss",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "19",
          "driver": "mortal",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "8,33%"
        },
        {
          "position": "20",
          "driver": "DIG Alezzo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "50,00%"
        }
      ],
      "Serie F": [
        {
          "position": "01",
          "driver": "Vizant",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "25,00%"
        },
        {
          "position": "02",
          "driver": "Pingo Pançudo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "25,00%"
        },
        {
          "position": "03",
          "driver": "Gonzav",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "20,00%"
        },
        {
          "position": "04",
          "driver": "Y.Oliveira",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "40,00%"
        },
        {
          "position": "05",
          "driver": "__Galego__",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "50,00%"
        },
        {
          "position": "06",
          "driver": "Banaannas",
          "country": "USA",
          "flag": "🇺🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "75,00%"
        },
        {
          "position": "07",
          "driver": "Zack7x",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "50,00%"
        },
        {
          "position": "08",
          "driver": "scoutzx",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "09",
          "driver": "WIZE",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "33,33%"
        },
        {
          "position": "10",
          "driver": "CF_a7x",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "66,67%"
        },
        {
          "position": "11",
          "driver": "Gonza1606",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "33,33%"
        },
        {
          "position": "12",
          "driver": "italianomtg",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "#N/A",
          "nc": 0,
          "dnf": "-"
        },
        {
          "position": "13",
          "driver": "Fawra",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "66,67%"
        },
        {
          "position": "14",
          "driver": "rickgudo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "15",
          "driver": "F2",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "16",
          "driver": "VSC - Gebe",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "17",
          "driver": "SirCartier",
          "country": "AUS",
          "flag": "🇦🇺",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "18",
          "driver": "LK GUIZERA",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "19",
          "driver": "AmaralJira",
          "country": "GHA",
          "flag": "🇬🇭",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "20",
          "driver": "Lary",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        }
      ],
      "Serie G": [
        {
          "position": "01",
          "driver": "Mateollll",
          "country": "SUI",
          "flag": "🇨🇭",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "02",
          "driver": "genaro_alma",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "03",
          "driver": "BRPRO Jotacê",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "04",
          "driver": "viyu99",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "05",
          "driver": "Nokapfacts",
          "country": "USA",
          "flag": "🇺🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "06",
          "driver": "ShortsKill",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "07",
          "driver": "dokho",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "08",
          "driver": "Koschei",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "09",
          "driver": "Nyxizem",
          "country": "TUR",
          "flag": "🇹🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "10",
          "driver": "breckdebs",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "11",
          "driver": "LH44DMC",
          "country": "GBR",
          "flag": "🇬🇧",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        },
        {
          "position": "12",
          "driver": "KingOfThegolpe",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "-"
        }
      ]
    }
  }
};
