window.sheetData = {
  "updatedAt": "2026-08-05T05:38:40.351Z",
  "f2": {
    "rankings": {
      "Serie A": [
        {
          "position": "01",
          "driver": "Not good",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 96.5,
          "pointsLabel": "96,50",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "02",
          "driver": "gootic",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 96.5,
          "pointsLabel": "96,50",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "03",
          "driver": "BreakingBench",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 90,
          "pointsLabel": "90,00",
          "movement": "🔼 + 1",
          "nc": 1,
          "dnf": "0,00%"
        },
        {
          "position": "04",
          "driver": "Gordão Do CS",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 89.5,
          "pointsLabel": "89,50",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "05",
          "driver": "vSpiritWilo",
          "country": "FRA",
          "flag": "🇫🇷",
          "team": "Sem construtor",
          "points": 79,
          "pointsLabel": "79,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "29,41%"
        },
        {
          "position": "06",
          "driver": "ViT1N",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 66,
          "pointsLabel": "66,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "14,29%"
        },
        {
          "position": "07",
          "driver": "Chimim00",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 63,
          "pointsLabel": "63,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "14,29%"
        },
        {
          "position": "08",
          "driver": "Rezende_rz",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 61.5,
          "pointsLabel": "61,50",
          "movement": "🔼 + 2",
          "nc": 2,
          "dnf": "16,67%"
        },
        {
          "position": "09",
          "driver": "JuninhoGameplay",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 61.5,
          "pointsLabel": "61,50",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "7,14%"
        },
        {
          "position": "10",
          "driver": "Glauco [BR]",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 57,
          "pointsLabel": "57,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "14,04%"
        },
        {
          "position": "11",
          "driver": "SNR_Tony",
          "country": "URU",
          "flag": "🇺🇾",
          "team": "Sem construtor",
          "points": 48,
          "pointsLabel": "48,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "28,57%"
        },
        {
          "position": "12",
          "driver": "Kimi_Antonellibr",
          "country": "NED",
          "flag": "🇳🇱",
          "team": "Sem construtor",
          "points": 46.5,
          "pointsLabel": "46,50",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "13",
          "driver": "Nego Ino",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 45,
          "pointsLabel": "45,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "30,00%"
        },
        {
          "position": "14",
          "driver": "reitor",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 44.5,
          "pointsLabel": "44,50",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "14,29%"
        },
        {
          "position": "15",
          "driver": "SBGF1_beco_nv",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 44,
          "pointsLabel": "44,00",
          "movement": "🔼 + 3",
          "nc": 3,
          "dnf": "12,50%"
        },
        {
          "position": "16",
          "driver": "PHX Erick",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 43,
          "pointsLabel": "43,00",
          "movement": "⏫ + 9",
          "nc": 9,
          "dnf": "18,52%"
        },
        {
          "position": "17",
          "driver": "danielmpipoca",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 42,
          "pointsLabel": "42,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "40,00%"
        },
        {
          "position": "18",
          "driver": "LeozeraBF",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 42,
          "pointsLabel": "42,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "0,00%"
        },
        {
          "position": "19",
          "driver": "V7_king_leo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 40,
          "pointsLabel": "40,00",
          "movement": "🔼 + 2",
          "nc": 2,
          "dnf": "0,00%"
        },
        {
          "position": "20",
          "driver": "italianomtg",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 39.5,
          "pointsLabel": "39,50",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "46,15%"
        }
      ],
      "Serie B": [
        {
          "position": "01",
          "driver": "BrunoCoutinhoC",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 33.5,
          "pointsLabel": "33,50",
          "movement": "⏫ + 35",
          "nc": 35,
          "dnf": "0,00%"
        },
        {
          "position": "02",
          "driver": "soylauta",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 33,
          "pointsLabel": "33,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "35,71%"
        },
        {
          "position": "03",
          "driver": "tbrenelli",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 32,
          "pointsLabel": "32,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "04",
          "driver": "vn",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 26.5,
          "pointsLabel": "26,50",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "16,67%"
        },
        {
          "position": "05",
          "driver": "CoyoteLoko",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 25,
          "pointsLabel": "25,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "34,78%"
        },
        {
          "position": "06",
          "driver": "PHMN",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 22,
          "pointsLabel": "22,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "41,18%"
        },
        {
          "position": "07",
          "driver": "mateusngv",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 21,
          "pointsLabel": "21,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "08",
          "driver": "PRTCarvalho",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 36,
          "pointsLabel": "36,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "14,29%"
        },
        {
          "position": "09",
          "driver": "Joao_livez",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 18,
          "pointsLabel": "18,00",
          "movement": "⏫ + 26",
          "nc": 26,
          "dnf": "33,33%"
        },
        {
          "position": "10",
          "driver": "luqinhas",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 17,
          "pointsLabel": "17,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "33,33%"
        },
        {
          "position": "11",
          "driver": "QuantumStern",
          "country": "MEX",
          "flag": "🇲🇽",
          "team": "Sem construtor",
          "points": 16,
          "pointsLabel": "16,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "0,00%"
        },
        {
          "position": "12",
          "driver": "LuizVitex",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 15,
          "pointsLabel": "15,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "14,81%"
        },
        {
          "position": "13",
          "driver": "RuanPbl",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 15,
          "pointsLabel": "15,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "15,38%"
        },
        {
          "position": "14",
          "driver": "Barbudo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 15,
          "pointsLabel": "15,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "11,76%"
        },
        {
          "position": "15",
          "driver": "XegZ",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 14,
          "pointsLabel": "14,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "0,00%"
        },
        {
          "position": "16",
          "driver": "TM Poseidon",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 13.5,
          "pointsLabel": "13,50",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "30,43%"
        },
        {
          "position": "17",
          "driver": "Moitipo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 12,
          "pointsLabel": "12,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "20,00%"
        },
        {
          "position": "18",
          "driver": "WLucas",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 11,
          "pointsLabel": "11,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "54,55%"
        },
        {
          "position": "19",
          "driver": "Killerthur",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 10,
          "pointsLabel": "10,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "33,33%"
        },
        {
          "position": "20",
          "driver": "Deadporco",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 7,
          "pointsLabel": "7,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "0,00%"
        }
      ],
      "Serie C": [
        {
          "position": "01",
          "driver": "Jfgame",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 6,
          "pointsLabel": "6,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "0,00%"
        },
        {
          "position": "02",
          "driver": "vdm$",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 6,
          "pointsLabel": "6,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "50,00%"
        },
        {
          "position": "03",
          "driver": "PDD_jaguatirica",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 6,
          "pointsLabel": "6,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "80,00%"
        },
        {
          "position": "04",
          "driver": "ReD",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "7,69%"
        },
        {
          "position": "05",
          "driver": "yoNumber",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "0,00%"
        },
        {
          "position": "06",
          "driver": "millo_bello",
          "country": "CZE",
          "flag": "🇨🇿",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "50,00%"
        },
        {
          "position": "07",
          "driver": "PaloTeroz_",
          "country": "EE",
          "flag": "🇪🇪",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "100,00%"
        },
        {
          "position": "08",
          "driver": "PuavaLT",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "0,00%"
        },
        {
          "position": "09",
          "driver": "Neves",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 9",
          "nc": 9,
          "dnf": "0,00%"
        },
        {
          "position": "10",
          "driver": "Lopbiel",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "11",
          "driver": "RICHGUAPP",
          "country": "IT",
          "flag": "🇮🇹",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "12",
          "driver": "andrxss",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "35,00%"
        },
        {
          "position": "13",
          "driver": "WORF",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "14",
          "driver": "F4CU",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "15",
          "driver": "pedro4462",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "0,00%"
        },
        {
          "position": "16",
          "driver": "lerid",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 3",
          "nc": -3,
          "dnf": "100,00%"
        },
        {
          "position": "17",
          "driver": "Andres10Dragon",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 77",
          "nc": 77,
          "dnf": "100,00%"
        },
        {
          "position": "18",
          "driver": "lipe0204",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "13,73%"
        },
        {
          "position": "19",
          "driver": "Paulo Inigo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "4,35%"
        },
        {
          "position": "20",
          "driver": "I_need_a_DOCTOR",
          "country": "CAN",
          "flag": "🇨🇦",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "29,63%"
        }
      ],
      "Serie D": [
        {
          "position": "01",
          "driver": "fjsapi",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "02",
          "driver": "Rodrigomaia_",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "4,76%"
        },
        {
          "position": "03",
          "driver": "Vegenakki",
          "country": "FIN",
          "flag": "🇫🇮",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "04",
          "driver": "Dudu Reeves",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "16,67%"
        },
        {
          "position": "05",
          "driver": "PHX_Srta_Dark_T",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "45,45%"
        },
        {
          "position": "06",
          "driver": "ValdineyGamer_YT",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "6,25%"
        },
        {
          "position": "07",
          "driver": "UrsoSenna",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "19,15%"
        },
        {
          "position": "08",
          "driver": "lucasKS",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "09",
          "driver": "GHR-ghostin",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "45,00%"
        },
        {
          "position": "10",
          "driver": "L1peZxZ",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "66,67%"
        },
        {
          "position": "11",
          "driver": "arleking",
          "country": "MEX",
          "flag": "🇲🇽",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "46,67%"
        },
        {
          "position": "12",
          "driver": "Sic-wolf",
          "country": "IT",
          "flag": "🇮🇹",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "33,33%"
        },
        {
          "position": "13",
          "driver": "Fer",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "33,33%"
        },
        {
          "position": "14",
          "driver": "Vizant",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "22,22%"
        },
        {
          "position": "15",
          "driver": "deri",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "47,37%"
        },
        {
          "position": "16",
          "driver": "Major",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "17",
          "driver": "junniorkz",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "33,33%"
        },
        {
          "position": "18",
          "driver": "IsmuYa",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "62,50%"
        },
        {
          "position": "19",
          "driver": "Liine e Teteu",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "20",
          "driver": "Enzo24M",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "23,53%"
        }
      ],
      "Serie E": [
        {
          "position": "01",
          "driver": "LucastBorges",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "02",
          "driver": "Kauesilvasp",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "03",
          "driver": "blid",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "04",
          "driver": "M10",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "05",
          "driver": "Fawra",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "75,00%"
        },
        {
          "position": "06",
          "driver": "willaxbox",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "07",
          "driver": "ARM BUNFL",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "08",
          "driver": "GAMER",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "09",
          "driver": "SCHUCHTER",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "10",
          "driver": "shadoww",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "11",
          "driver": "Alexander_Gui",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "71,43%"
        },
        {
          "position": "12",
          "driver": "murf",
          "country": "THA",
          "flag": "🇹🇭",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "13",
          "driver": "Puga",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "14",
          "driver": "DiegoAnonimo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "15",
          "driver": "Max Verstappen",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "22,22%"
        },
        {
          "position": "16",
          "driver": "ARM_Theuz_B",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "25,00%"
        },
        {
          "position": "17",
          "driver": "Waitz",
          "country": "COL",
          "flag": "🇨🇴",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "27,78%"
        },
        {
          "position": "18",
          "driver": "deharo",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "19",
          "driver": "Pudim-sweet",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "20",
          "driver": "Albono",
          "country": "THA",
          "flag": "🇹🇭",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        }
      ],
      "Serie F": [
        {
          "position": "01",
          "driver": "DH",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "02",
          "driver": "Tin84cho",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "19,05%"
        },
        {
          "position": "03",
          "driver": "[CRE] Kobayashi",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "04",
          "driver": "Inácio Souza",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "05",
          "driver": "Syrunn abandit",
          "country": "TUR",
          "flag": "🇹🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "06",
          "driver": "Alteim",
          "country": "NED",
          "flag": "🇳🇱",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "07",
          "driver": "FHOPO6",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "08",
          "driver": "Ninetty",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "63,64%"
        },
        {
          "position": "09",
          "driver": "Alan Zovedi",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "10",
          "driver": "Murilin",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "11",
          "driver": "fawk",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "12",
          "driver": "PolarBear",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "13",
          "driver": "Gustavo COSTA",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "14",
          "driver": "Cabecaloko",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "66,67%"
        },
        {
          "position": "15",
          "driver": "and0nii_s",
          "country": "USA",
          "flag": "🇺🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "16",
          "driver": "Levelupnarok",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "17",
          "driver": "RaphaelN",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "18",
          "driver": "Maxlp",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "19",
          "driver": "Marl5zxx",
          "country": "GBR",
          "flag": "🇬🇧",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "20",
          "driver": "LeonardoNeto",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "66,67%"
        }
      ],
      "Serie G": [
        {
          "position": "01",
          "driver": "Auxiliar de Construção Civil",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "02",
          "driver": "Alejo_Carballo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "03",
          "driver": "BRV-MIQUELOTI",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "04",
          "driver": "pudim_doce",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "05",
          "driver": "tavares_nt",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "06",
          "driver": "DELTA_Theuxzss",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "07",
          "driver": "mortal",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "8,33%"
        },
        {
          "position": "08",
          "driver": "REL MONTANAS",
          "country": "COL",
          "flag": "🇨🇴",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "#N/A",
          "nc": 0,
          "dnf": "-"
        },
        {
          "position": "09",
          "driver": "VSC - Gebe",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 70",
          "nc": 70,
          "dnf": "0,00%"
        },
        {
          "position": "10",
          "driver": "LK GUIZERA",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 70",
          "nc": 70,
          "dnf": "0,00%"
        },
        {
          "position": "11",
          "driver": "AmaralJira",
          "country": "GHA",
          "flag": "🇬🇭",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 70",
          "nc": 70,
          "dnf": "0,00%"
        },
        {
          "position": "12",
          "driver": "Niczera",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 70",
          "nc": 70,
          "dnf": "-"
        },
        {
          "position": "13",
          "driver": "CLV Jullian Vinicius",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 70",
          "nc": 70,
          "dnf": "-"
        },
        {
          "position": "14",
          "driver": "SGC-RICHIE",
          "country": "MEX",
          "flag": "🇲🇽",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 70",
          "nc": 70,
          "dnf": "-"
        },
        {
          "position": "15",
          "driver": "Isaac Soto",
          "country": "MEX",
          "flag": "🇲🇽",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 70",
          "nc": 70,
          "dnf": "-"
        }
      ]
    }
  }
};
