window.sheetData = {
  "updatedAt": "2026-08-01T05:47:52.998Z",
  "f2": {
    "rankings": {
      "Serie A": [
        {
          "position": "01",
          "driver": "gootic",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 96.5,
          "pointsLabel": "96,50",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "02",
          "driver": "Not good",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 89.5,
          "pointsLabel": "89,50",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "03",
          "driver": "Gordão Do CS",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 89.5,
          "pointsLabel": "89,50",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "04",
          "driver": "BreakingBench",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 80,
          "pointsLabel": "80,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "05",
          "driver": "vSpiritWilo",
          "country": "FRA",
          "flag": "🇫🇷",
          "team": "Sem construtor",
          "points": 79,
          "pointsLabel": "79,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "29,41%"
        },
        {
          "position": "06",
          "driver": "ViT1N",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 64.5,
          "pointsLabel": "64,50",
          "movement": "🔼 + 2",
          "nc": 2,
          "dnf": "15,15%"
        },
        {
          "position": "07",
          "driver": "Chimim00",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 63,
          "pointsLabel": "63,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "14,29%"
        },
        {
          "position": "08",
          "driver": "JuninhoGameplay",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 61.5,
          "pointsLabel": "61,50",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "7,14%"
        },
        {
          "position": "09",
          "driver": "Glauco [BR]",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 57,
          "pointsLabel": "57,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "14,55%"
        },
        {
          "position": "10",
          "driver": "Rezende_rz",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 51.5,
          "pointsLabel": "51,50",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "17,02%"
        },
        {
          "position": "11",
          "driver": "SNR_Tony",
          "country": "URU",
          "flag": "🇺🇾",
          "team": "Sem construtor",
          "points": 48,
          "pointsLabel": "48,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "28,57%"
        },
        {
          "position": "12",
          "driver": "Kimi_Antonellibr",
          "country": "NED",
          "flag": "🇳🇱",
          "team": "Sem construtor",
          "points": 46.5,
          "pointsLabel": "46,50",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "13",
          "driver": "reitor",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 44.5,
          "pointsLabel": "44,50",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "14,29%"
        },
        {
          "position": "14",
          "driver": "danielmpipoca",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 42,
          "pointsLabel": "42,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "40,00%"
        },
        {
          "position": "15",
          "driver": "LeozeraBF",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 42,
          "pointsLabel": "42,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "16",
          "driver": "Nego Ino",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 42,
          "pointsLabel": "42,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "25,00%"
        },
        {
          "position": "17",
          "driver": "SBGF1_beco_nv",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 40.5,
          "pointsLabel": "40,50",
          "movement": "🔼 + 1",
          "nc": 1,
          "dnf": "14,29%"
        },
        {
          "position": "18",
          "driver": "italianomtg",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 38.5,
          "pointsLabel": "38,50",
          "movement": "⏫ + 10",
          "nc": 10,
          "dnf": "46,15%"
        },
        {
          "position": "19",
          "driver": "soylauta",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 33,
          "pointsLabel": "33,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "35,71%"
        },
        {
          "position": "20",
          "driver": "V7_king_leo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 30,
          "pointsLabel": "30,00",
          "movement": "⏫ + 6",
          "nc": 6,
          "dnf": "0,00%"
        }
      ],
      "Serie B": [
        {
          "position": "01",
          "driver": "vn",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 26.5,
          "pointsLabel": "26,50",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "16,67%"
        },
        {
          "position": "02",
          "driver": "CoyoteLoko",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 25,
          "pointsLabel": "25,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "34,78%"
        },
        {
          "position": "03",
          "driver": "tbrenelli",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 24,
          "pointsLabel": "24,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "0,00%"
        },
        {
          "position": "04",
          "driver": "PHMN",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 22,
          "pointsLabel": "22,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "41,18%"
        },
        {
          "position": "05",
          "driver": "PHX Erick",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 21.5,
          "pointsLabel": "21,50",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "19,23%"
        },
        {
          "position": "06",
          "driver": "mateusngv",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 21,
          "pointsLabel": "21,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "0,00%"
        },
        {
          "position": "07",
          "driver": "PRTCarvalho",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 18,
          "pointsLabel": "18,00",
          "movement": "🔽 - 2",
          "nc": -2,
          "dnf": "14,81%"
        },
        {
          "position": "08",
          "driver": "luqinhas",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 17,
          "pointsLabel": "17,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "33,33%"
        },
        {
          "position": "09",
          "driver": "QuantumStern",
          "country": "MEX",
          "flag": "🇲🇽",
          "team": "Sem construtor",
          "points": 16,
          "pointsLabel": "16,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "10",
          "driver": "LuizVitex",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 15,
          "pointsLabel": "15,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "14,81%"
        },
        {
          "position": "11",
          "driver": "RuanPbl",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 15,
          "pointsLabel": "15,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "15,38%"
        },
        {
          "position": "12",
          "driver": "Barbudo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 15,
          "pointsLabel": "15,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "11,76%"
        },
        {
          "position": "13",
          "driver": "TM Poseidon",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 13.5,
          "pointsLabel": "13,50",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "30,43%"
        },
        {
          "position": "14",
          "driver": "Moitipo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 12,
          "pointsLabel": "12,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "20,00%"
        },
        {
          "position": "15",
          "driver": "WLucas",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 11,
          "pointsLabel": "11,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "54,55%"
        },
        {
          "position": "16",
          "driver": "Killerthur",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 10,
          "pointsLabel": "10,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "33,33%"
        },
        {
          "position": "17",
          "driver": "Deadporco",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 7,
          "pointsLabel": "7,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "18",
          "driver": "XegZ",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 7,
          "pointsLabel": "7,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "19",
          "driver": "Jfgame",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 6,
          "pointsLabel": "6,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "20",
          "driver": "vdm$",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 6,
          "pointsLabel": "6,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "50,00%"
        }
      ],
      "Serie C": [
        {
          "position": "01",
          "driver": "PDD_jaguatirica",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 6,
          "pointsLabel": "6,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "77,78%"
        },
        {
          "position": "02",
          "driver": "ReD",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "8,00%"
        },
        {
          "position": "03",
          "driver": "yoNumber",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "04",
          "driver": "millo_bello",
          "country": "CZE",
          "flag": "🇨🇿",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "50,00%"
        },
        {
          "position": "05",
          "driver": "PaloTeroz_",
          "country": "EE",
          "flag": "🇪🇪",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "100,00%"
        },
        {
          "position": "06",
          "driver": "PuavaLT",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "07",
          "driver": "Lopbiel",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "100,00%"
        },
        {
          "position": "08",
          "driver": "RICHGUAPP",
          "country": "IT",
          "flag": "🇮🇹",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "09",
          "driver": "andrxss",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "35,00%"
        },
        {
          "position": "10",
          "driver": "WORF",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "100,00%"
        },
        {
          "position": "11",
          "driver": "F4CU",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "100,00%"
        },
        {
          "position": "12",
          "driver": "pedro4462",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "◀️ = 0",
          "nc": 0,
          "dnf": "0,00%"
        },
        {
          "position": "13",
          "driver": "lerid",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 91",
          "nc": 91,
          "dnf": "100,00%"
        },
        {
          "position": "14",
          "driver": "lipe0204",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "13,73%"
        },
        {
          "position": "15",
          "driver": "Paulo Inigo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "4,35%"
        },
        {
          "position": "16",
          "driver": "I_need_a_DOCTOR",
          "country": "CAN",
          "flag": "🇨🇦",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "29,63%"
        },
        {
          "position": "17",
          "driver": "fjsapi",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "18",
          "driver": "Rodrigomaia_",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "4,76%"
        },
        {
          "position": "19",
          "driver": "PMT JoaoTwcod",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "25,00%"
        },
        {
          "position": "20",
          "driver": "Vegenakki",
          "country": "FIN",
          "flag": "🇫🇮",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        }
      ],
      "Serie D": [
        {
          "position": "01",
          "driver": "Zana",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "02",
          "driver": "Dudu Reeves",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "16,67%"
        },
        {
          "position": "03",
          "driver": "PHX_Srta_Dark_T",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "45,45%"
        },
        {
          "position": "04",
          "driver": "ValdineyGamer_YT",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "6,25%"
        },
        {
          "position": "05",
          "driver": "UrsoSenna",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "19,15%"
        },
        {
          "position": "06",
          "driver": "lucasKS",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "07",
          "driver": "GHR-ghostin",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "45,00%"
        },
        {
          "position": "08",
          "driver": "L1peZxZ",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "66,67%"
        },
        {
          "position": "09",
          "driver": "arleking",
          "country": "MEX",
          "flag": "🇲🇽",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "46,67%"
        },
        {
          "position": "10",
          "driver": "Sic-wolf",
          "country": "IT",
          "flag": "🇮🇹",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "33,33%"
        },
        {
          "position": "11",
          "driver": "Fer",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "33,33%"
        },
        {
          "position": "12",
          "driver": "Vizant",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "22,22%"
        },
        {
          "position": "13",
          "driver": "deri",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "47,37%"
        },
        {
          "position": "14",
          "driver": "Major",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "15",
          "driver": "junniorkz",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "33,33%"
        },
        {
          "position": "16",
          "driver": "IsmuYa",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "62,50%"
        },
        {
          "position": "17",
          "driver": "Liine e Teteu",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "18",
          "driver": "Enzo24M",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "23,53%"
        },
        {
          "position": "19",
          "driver": "LucastBorges",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "20",
          "driver": "Kauesilvasp",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        }
      ],
      "Serie E": [
        {
          "position": "01",
          "driver": "blid",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "02",
          "driver": "M10",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "03",
          "driver": "Fawra",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "75,00%"
        },
        {
          "position": "04",
          "driver": "willaxbox",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "05",
          "driver": "ARM BUNFL",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "06",
          "driver": "GAMER",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "07",
          "driver": "SCHUCHTER",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "08",
          "driver": "shadoww",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "09",
          "driver": "Alexander_Gui",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "71,43%"
        },
        {
          "position": "10",
          "driver": "murf",
          "country": "THA",
          "flag": "🇹🇭",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "11",
          "driver": "Puga",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "12",
          "driver": "DiegoAnonimo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "13",
          "driver": "Max Verstappen",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "22,22%"
        },
        {
          "position": "14",
          "driver": "ARM_Theuz_B",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "25,00%"
        },
        {
          "position": "15",
          "driver": "Waitz",
          "country": "COL",
          "flag": "🇨🇴",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "27,78%"
        },
        {
          "position": "16",
          "driver": "deharo",
          "country": "ESP",
          "flag": "🇪🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "17",
          "driver": "Pudim-sweet",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "18",
          "driver": "Albono",
          "country": "THA",
          "flag": "🇹🇭",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "19",
          "driver": "DH",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "20",
          "driver": "Tin84cho",
          "country": "ARG",
          "flag": "🇦🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "19,05%"
        }
      ],
      "Serie F": [
        {
          "position": "01",
          "driver": "[CRE] Kobayashi",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "02",
          "driver": "Inácio Souza",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "03",
          "driver": "Syrunn abandit",
          "country": "TUR",
          "flag": "🇹🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "04",
          "driver": "Alteim",
          "country": "NED",
          "flag": "🇳🇱",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "05",
          "driver": "FHOPO6",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "06",
          "driver": "Ninetty",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "63,64%"
        },
        {
          "position": "07",
          "driver": "Alan Zovedi",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "08",
          "driver": "Murilin",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "09",
          "driver": "fawk",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "10",
          "driver": "PolarBear",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "11",
          "driver": "Gustavo COSTA",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "12",
          "driver": "Cabecaloko",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "66,67%"
        },
        {
          "position": "13",
          "driver": "and0nii_s",
          "country": "USA",
          "flag": "🇺🇸",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "14",
          "driver": "Levelupnarok",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "15",
          "driver": "RaphaelN",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "16",
          "driver": "Maxlp",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "17",
          "driver": "Marl5zxx",
          "country": "GBR",
          "flag": "🇬🇧",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "18",
          "driver": "LeonardoNeto",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "66,67%"
        },
        {
          "position": "19",
          "driver": "Auxiliar de Construção Civil",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "20",
          "driver": "BrunoCoutinhoC",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        }
      ],
      "Serie G": [
        {
          "position": "01",
          "driver": "Alejo_Carballo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "02",
          "driver": "BRV-MIQUELOTI",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "03",
          "driver": "pudim_doce",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "04",
          "driver": "tavares_nt",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "05",
          "driver": "DELTA_Theuxzss",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "100,00%"
        },
        {
          "position": "06",
          "driver": "mortal",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "8,33%"
        },
        {
          "position": "07",
          "driver": "Pingo Pançudo",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "25,00%"
        },
        {
          "position": "08",
          "driver": "Y.Oliveira",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "40,00%"
        },
        {
          "position": "09",
          "driver": "__Galego__",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "10",
          "driver": "Zack7x",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "50,00%"
        },
        {
          "position": "11",
          "driver": "scoutzx",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "12",
          "driver": "BZK_tahariel",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "13",
          "driver": "VSC - Gebe",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "14",
          "driver": "SirCartier",
          "country": "AUS",
          "flag": "🇦🇺",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "15",
          "driver": "LK GUIZERA",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "16",
          "driver": "AmaralJira",
          "country": "GHA",
          "flag": "🇬🇭",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "0,00%"
        },
        {
          "position": "17",
          "driver": "Niczera",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "18",
          "driver": "CLV Jullian Vinicius",
          "country": "BRA",
          "flag": "🇧🇷",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "🔽 - 1",
          "nc": -1,
          "dnf": "-"
        },
        {
          "position": "19",
          "driver": "SGC-RICHIE",
          "country": "MEX",
          "flag": "🇲🇽",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 85",
          "nc": 85,
          "dnf": "-"
        },
        {
          "position": "20",
          "driver": "Isaac Soto",
          "country": "MEX",
          "flag": "🇲🇽",
          "team": "Sem construtor",
          "points": 0,
          "pointsLabel": "0,00",
          "movement": "⏫ + 85",
          "nc": 85,
          "dnf": "-"
        }
      ]
    }
  }
};
